### ISSUE TITLE
Clean up Paper 2, WCCI

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/Wearables-Research#15]
Meeting Notes: https://docs.google.com/document/d/1l20QhCBcyUZYxQReJ4r-g3jzH9Bvk_qIq3RYpq8WIAM/edit?usp=sharing

- [x] Matt
  - [x] Review written sections
    - [x] Section 1
    - [x] Section 2
    - [x] Section 3
    - [x] Section 4
    - [x] Experimental Design
    - [x] Results
- [x] Glavin
  - [x] Review of Tables
    - [x] [Precision & Recall](https://en.wikipedia.org/wiki/Precision_and_recall) tables
      - Suppose a computer program for recognizing dogs in scenes from a video identifies 7 dogs in a scene containing 9 dogs and some cats. If 4 of the identifications are correct, but 3 are actually cats, the program's precision is 4/7 while its recall is 4/9. 
      - When a search engine returns 30 pages only 20 of which were relevant while failing to return 40 additional relevant pages, its precision is 20/30 = 2/3 while its recall is 20/60 = 1/3.
So, in this case, precision is 'how useful the search results are', and recall is 'how complete the results are'.
  - [x] Calculate the 25% and 75% for the entire dataset
  - [x] Review written sections
    - [x] Section 1
    - [x] Section 2
    - [x] Section 3
    - [x] Section 4
    - [x] Experimental Design (wait until Matt is done)
    - [x] Results (wait until Matt is done)
  - [x] At the end of section V, please add some details on why the two
individuals we recorded data for were later excluded
  - [x] Please specifically take a look at the numbers in the Knowledge
Representation section, I know some of the numbers need to be updated based
on what the final dataset consisted of.
  - [x] recreate the two graph images we're using with a larger
font on the title and axes

**Comment by mtriff** [comment]
Hi Glavin,

The papers have been merged and sections I-VII are ready for your review.

Some comments:
- At the end of section V, please add some details on why the two
individuals we recorded data for were later excluded
- Please specifically take a look at the numbers in the Knowledge
Representation section, I know some of the numbers need to be updated based
on what the final dataset consisted of.
- Is it possible to recreate the two graph images we're using with a larger
font on the title and axes?
- I have yet to add the relevant references from Ref.bib from the CdnAI
paper to the bibliography, those will be added by the end of the week.

I'll have the remaining sections ready for your review by midweek.

Thank you,
Matt

**Comment by Glavin001** [comment]
Thanks, Matt. I have added your comments to my TODO list above. Will let you know if I have any questions.

**Comment by Glavin001** [comment]
@glavin001 : Merge the latest changes from https://drive.google.com/open?id=0B_8jqE2v0W14RmNnS3VGX1FOMGM and finish off reviewing.

**Comment by Glavin001** [comment]
@mtriff what do you think of these revised graphs?
![image](https://cloud.githubusercontent.com/assets/1885333/12693695/2de86d9a-c6e8-11e5-91ea-4a4b28d0c78e.png)

Let me know if there are *any* changes you would like me to make :smiley:.

**Comment by Glavin001** [comment]
For reference, this is what they looked like before:
![image](https://cloud.githubusercontent.com/assets/1885333/12693701/707c96f4-c6e8-11e5-8172-9577eede6103.png)

I scaled their size by 2.

**Comment by Glavin001** [comment]
@pawanLingras , @mtriff : Could you elaborate on what the `NNN` value would represent in this case (page 4, top of right column)?

> As we can see the representation consists of only NNN values and captures the essence of each wave, position, and person in a concise and consistent manner. 

My instinct was NNN = 160 values, since that is how we represent a single session. 
However the next sentence is:

> Since we have a total of four positions, five waves, and eight histogram bins, we have a total of 4×5×8 = 160 values to represent each record of an activity. 

Which indicates to me that the NNN in the previous sentence should be something different.

**Comment by mtriff** [comment]
The graphs look much better, thanks.

I will leave your second question to Pawan.

Thanks,
Matt

**Comment by Glavin001** [comment]
In section 1 it says:
> The approach is tested for a data collection consisting of five individuals who performed a number of everyday tasks such as listening to music, reading, playing computer games, relaxing, or web surfing.

Our activities were actually:
- music
- reading
- game
- none
- video

So would `relaxing = none` and `web surfing = video`?

**Comment by Glavin001** [comment]
> - At the end of section V, please add some details on why the two
individuals we recorded data for were later excluded

I added:
> There were technical problems with the data collection that left individuals with an insufficient amount of data. After experimenting with our dataset we determined that this caused a bias towards certain individuals and we therefore decided to exclude two individuals from the dataset entirely.
This resulted in a final total of twenty-four datasets.

I may need your assistance @mtriff to ensure the writing is similar to the rest of the paper.
