### ISSUE TITLE
10-fold Cross Validation using rpart

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/Wearables-Research#7]
## Paper 1

- Use `rpart`
- [x] 10-fold cross validation
  - [x] take 10% of the data out
  - [x] train on 90%
  - [x] test on 10%
  - [x] repeat with different 10% set
  - Use [cvtools](http://cran.r-project.org/web/packages/cvTools/cvTools.pdf)

---

- [ ] Write a section on what MUSE is
  - How data is collecting from 4 different spots
  - What each signals mean

---

- [ ] Create our own datasets
- [ ] Predict activities
  - Questions:
    - Are different games creating different results? Angry Birds versus another game?

---

## Paper 2

- [ ] Use [Random Forest](http://cran.r-project.org/web/packages/randomForest/randomForest.pdf)
  - [x] Find important variables, using `importance`
  - [x] Use important variables for cluster
    - See if clusters are activities
    - [x] Use other set of important variables for clusters for activities than person

---

## Paper 3

- Fuzzy cluster
- comparing clustering results versus classification

**Comment by Glavin001** [comment]
I switched to using Caret's 10-fold cross-validation. See `Repeated k-fold Cross Validation` in http://machinelearningmastery.com/how-to-estimate-model-accuracy-in-r-using-the-caret-package/

**Comment by Glavin001** [comment]
Simple guide to confusion matrix terminology: http://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/

**Comment by Glavin001** [comment]
@pawanLingras @mtriff : Should I be dividing the frequencies from the histogram bins by the total # of rows to normalize the values for longer and shorter sessions?

Currently, I generate the histogram:

```r
h.norm <- hist(curr.data.norm, main = header, xlab = header, breaks = breaks.norm, plot = plotting)
```

And then use the `$counts` (frequencies for each bin):

```r
h.norm$counts
```

Applicable code: https://github.com/Glavin001/Wearables-Research/blob/master/src/stats.R#L156-L168

However the more that I think about it, I should be using something closer to `$counts / N` where `N` is the # of rows, `nrow(curr.data.norm)`.

I do normalize the values with 90% of the maximum: https://github.com/Glavin001/Wearables-Research/blob/master/src/stats.R#L145-L148
The problem I am seeing is that the maximum frequency for a bin could be inflated by a longer session, such that a 2 times longer session might have roughly 2 times the number of records in that bin now, given the same activity and/or person.

**Comment by pawanLingras** [comment]
I do not see a need for normalization of values.  Percentile takes care of
length of time series

**Comment by Glavin001** [comment]
Useful links:
- xtables gallary: https://cran.r-project.org/web/packages/xtable/vignettes/xtableGallery.pdf
- LaTeX/Bibliography Management: https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management
- 5 Types Of Brain Waves Frequencies: Gamma, Beta, Alpha, Theta, Delta: http://mentalhealthdaily.com/2014/04/15/5-types-of-brain-waves-frequencies-gamma-beta-alpha-theta-delta/
- how to text-wrap an image in latex: http://tex.stackexchange.com/questions/118602/how-to-text-wrap-an-image-in-latex
